allowBuilds:
    esbuild: true
    msgpackr-extract: true
minimumReleaseAgeExclude:
    - "@effect/platform-node-shared@4.0.0-beta.75"
    - "@effect/platform-node@4.0.0-beta.75"
    - effect@4.0.0-beta.75
    - "@effect/platform-node-shared@4.0.0-beta.75"
    - "@effect/platform-node@4.0.0-beta.75"
    - "@oxfmt/binding-android-arm-eabi@0.53.0"
    - "@oxfmt/binding-android-arm64@0.53.0"
    - "@oxfmt/binding-darwin-arm64@0.53.0"
    - "@oxfmt/binding-darwin-x64@0.53.0"
    - "@oxfmt/binding-freebsd-x64@0.53.0"
    - "@oxfmt/binding-linux-arm-gnueabihf@0.53.0"
    - "@oxfmt/binding-linux-arm-musleabihf@0.53.0"
    - "@oxfmt/binding-linux-arm64-gnu@0.53.0"
    - "@oxfmt/binding-linux-arm64-musl@0.53.0"
    - "@oxfmt/binding-linux-ppc64-gnu@0.53.0"
    - "@oxfmt/binding-linux-riscv64-gnu@0.53.0"
    - "@oxfmt/binding-linux-riscv64-musl@0.53.0"
    - "@oxfmt/binding-linux-s390x-gnu@0.53.0"
    - "@oxfmt/binding-linux-x64-gnu@0.53.0"
    - "@oxfmt/binding-linux-x64-musl@0.53.0"
    - "@oxfmt/binding-openharmony-arm64@0.53.0"
    - "@oxfmt/binding-win32-arm64-msvc@0.53.0"
    - "@oxfmt/binding-win32-ia32-msvc@0.53.0"
    - "@oxfmt/binding-win32-x64-msvc@0.53.0"
    - effect@4.0.0-beta.75
    - oxfmt@0.53.0
