allowBuilds:
    esbuild: true
    msgpackr-extract: true
minimumReleaseAgeExclude:
    - "@effect/platform-node-shared@4.0.0-beta.70"
    - "@effect/platform-node@4.0.0-beta.70"
    - effect@4.0.0-beta.70
